import = [
    "~/.config/alacritty/themes/themes/cyber_punk.toml"
]
[window]
decorations = "Transparent"
opacity = 0.9
[font]
normal ={family="firacode nerd font",style="regular"}
size=7
[cursor]
style = { shape = "Beam" , blinking = "Always" }
